version: '3.8'

services:
  db:
    platform: linux/x86_64 # M1チップ用
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/db:/var/lib/mysql
      - ./docker/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - 3306:3306